import type { CityState } from "./types";

export const initialCityState: CityState = {
  tick: 0,
  day: 1,
  hour: 8,
  resources: {
    food: 68,
    materials: 42,
    credits: 460,
  },
  scenario: {
    id: "pure_capital_frontier",
    name: "Pure Capital Frontier",
    description: "A high-freedom market scenario with weak welfare and rising faction tension.",
    economyModel: "pure_capitalism",
    conflictState: "unrest",
    marketFreedom: 92,
    welfareLevel: 12,
    conflictPressure: 58,
  },
  districts: [
    { id: "homes", name: "Harbor Apartments", kind: "residential", stability: 82 },
    { id: "farm", name: "Green Labs", kind: "farm", stability: 76 },
    { id: "market", name: "Glass Market", kind: "market", stability: 68 },
    { id: "civic", name: "Civic Plaza", kind: "civic", stability: 73 },
    { id: "workshop", name: "Maker Quarter", kind: "work", stability: 61 },
    { id: "hospital", name: "Northside Hospital", kind: "hospital", stability: 79 },
    { id: "police", name: "Central Police Station", kind: "police", stability: 67 },
    { id: "prison", name: "Civic Detention Center", kind: "prison", stability: 58 },
  ],
  structures: [
    {
      id: "structure_homes",
      name: "Harbor Apartments",
      kind: "residential",
      districtId: "homes",
      position: { x: 16.2, y: 65.8 },
      functions: ["rest", "socialize", "relocate"],
    },
    {
      id: "structure_green_labs",
      name: "Green Labs",
      kind: "farm",
      districtId: "farm",
      position: { x: 73.0, y: 80.1 },
      functions: ["work"],
    },
    {
      id: "structure_glass_market",
      name: "Glass Market",
      kind: "market",
      districtId: "market",
      position: { x: 83.2, y: 67.1 },
      functions: ["buy_food", "work", "exploit_market", "socialize"],
    },
    {
      id: "structure_city_hall",
      name: "City Hall",
      kind: "civic",
      districtId: "civic",
      position: { x: 49.4, y: 38.8 },
      functions: ["help_neighbor", "mediate_conflict", "faction_campaign", "study"],
    },
    {
      id: "structure_maker_quarter",
      name: "Maker Quarter",
      kind: "work",
      districtId: "workshop",
      position: { x: 49.5, y: 84.1 },
      functions: ["work"],
    },
    {
      id: "structure_hospital",
      name: "Northside Hospital",
      kind: "hospital",
      districtId: "hospital",
      position: { x: 21.3, y: 20.6 },
      functions: ["hospital_treatment", "work"],
    },
    {
      id: "structure_police",
      name: "Central Police Station",
      kind: "police",
      districtId: "police",
      position: { x: 18.0, y: 45.6 },
      functions: ["report_crime", "police_patrol", "arrest_citizen", "work"],
    },
    {
      id: "structure_detention",
      name: "Civic Detention Center",
      kind: "prison",
      districtId: "prison",
      position: { x: 78.2, y: 18.4 },
      functions: ["rest"],
    },
  ],
  roads: [
    {
      id: "road_harbor_police",
      name: "Harbor Service Road",
      fromStructureId: "structure_homes",
      toStructureId: "structure_police",
      kind: "secondary",
    },
    {
      id: "road_police_hospital",
      name: "North Civic Avenue",
      fromStructureId: "structure_police",
      toStructureId: "structure_hospital",
      kind: "primary",
    },
    {
      id: "road_police_city_hall",
      name: "Central Civic Way",
      fromStructureId: "structure_police",
      toStructureId: "structure_city_hall",
      kind: "primary",
    },
    {
      id: "road_hospital_city_hall",
      name: "Clinic Connector",
      fromStructureId: "structure_hospital",
      toStructureId: "structure_city_hall",
      kind: "secondary",
    },
    {
      id: "road_city_hall_maker",
      name: "Maker Spine",
      fromStructureId: "structure_city_hall",
      toStructureId: "structure_maker_quarter",
      kind: "primary",
    },
    {
      id: "road_harbor_maker",
      name: "Harbor Freight Road",
      fromStructureId: "structure_homes",
      toStructureId: "structure_maker_quarter",
      kind: "secondary",
    },
    {
      id: "road_maker_market",
      name: "Foundry Market Road",
      fromStructureId: "structure_maker_quarter",
      toStructureId: "structure_glass_market",
      kind: "primary",
    },
    {
      id: "road_market_green_labs",
      name: "Greenway",
      fromStructureId: "structure_glass_market",
      toStructureId: "structure_green_labs",
      kind: "secondary",
    },
    {
      id: "road_maker_green_labs",
      name: "Agritech Lane",
      fromStructureId: "structure_maker_quarter",
      toStructureId: "structure_green_labs",
      kind: "service",
      travelMultiplier: 1.15,
    },
    {
      id: "road_city_hall_detention",
      name: "Detention Causeway",
      fromStructureId: "structure_city_hall",
      toStructureId: "structure_detention",
      kind: "secondary",
      travelMultiplier: 1.1,
    },
    {
      id: "road_market_detention",
      name: "East Gate Road",
      fromStructureId: "structure_glass_market",
      toStructureId: "structure_detention",
      kind: "service",
      travelMultiplier: 1.2,
    },
  ],
  institutions: [
    {
      id: "institution_civic",
      name: "City Hall",
      kind: "civic",
      districtId: "civic",
      capacity: 20,
      staffing: 64,
      publicTrust: 58,
      load: 0,
    },
    {
      id: "institution_hospital",
      name: "Northside Hospital",
      kind: "hospital",
      districtId: "hospital",
      capacity: 8,
      staffing: 72,
      publicTrust: 69,
      load: 0,
    },
    {
      id: "institution_police",
      name: "Central Police Station",
      kind: "police",
      districtId: "police",
      capacity: 6,
      staffing: 58,
      publicTrust: 52,
      load: 2,
    },
    {
      id: "institution_prison",
      name: "Civic Detention Center",
      kind: "prison",
      districtId: "prison",
      capacity: 5,
      staffing: 49,
      publicTrust: 42,
      load: 0,
    },
  ],
  metrics: {
    publicSafety: 57,
    publicHealth: 72,
    crimeReports: 2,
    openCases: 2,
    hospitalLoad: 0,
    prisonLoad: 0,
  },
  factions: [
    {
      id: "guild",
      name: "Workers Guild",
      agenda: "labor",
      funds: 74,
      influence: 48,
      hostility: 36,
    },
    {
      id: "exchange",
      name: "Free Exchange League",
      agenda: "capital",
      funds: 160,
      influence: 62,
      hostility: 44,
    },
    {
      id: "council",
      name: "Civic Council",
      agenda: "civic",
      funds: 118,
      influence: 57,
      hostility: 24,
    },
    {
      id: "shadows",
      name: "Shadow Brokers",
      agenda: "underground",
      funds: 42,
      influence: 21,
      hostility: 68,
    },
  ],
  jobs: [
    {
      id: "farm_job",
      name: "Farm Shift",
      kind: "farmer",
      districtId: "farm",
      wage: 9,
      energyCost: 16,
      produces: { food: 8 },
    },
    {
      id: "bakery_job",
      name: "Bakery Shift",
      kind: "baker",
      districtId: "market",
      wage: 11,
      energyCost: 18,
      produces: { food: 5, credits: 2 },
    },
    {
      id: "builder_job",
      name: "Repair Crew",
      kind: "builder",
      districtId: "workshop",
      wage: 13,
      energyCost: 22,
      produces: { materials: 7 },
    },
    {
      id: "clinic_job",
      name: "Hospital Aid",
      kind: "medic",
      districtId: "hospital",
      wage: 10,
      energyCost: 14,
      produces: { credits: 3 },
    },
    {
      id: "police_job",
      name: "Public Safety Shift",
      kind: "officer",
      districtId: "police",
      wage: 12,
      energyCost: 18,
      produces: { credits: 2 },
    },
    {
      id: "trade_job",
      name: "Market Broker",
      kind: "trader",
      districtId: "market",
      wage: 12,
      energyCost: 17,
      produces: { credits: 6 },
    },
  ],
  citizens: [
    {
      id: "citizen_anna",
      name: "Anna",
      role: "farmer",
      districtId: "farm",
      destinationDistrictId: "homes",
      factionId: "guild",
      money: 24,
      hunger: 38,
      energy: 74,
      mood: 71,
      reputation: 58,
      status: "active",
      position: { x: 73.0, y: 80.1 },
      currentAction: "work",
      personality: {
        morality: 82,
        empathy: 76,
        ambition: 48,
        risk: 22,
        traits: ["generous", "disciplined"],
      },
    },
    {
      id: "citizen_milo",
      name: "Milo",
      role: "trader",
      districtId: "market",
      destinationDistrictId: "market",
      factionId: "exchange",
      money: 41,
      hunger: 44,
      energy: 66,
      mood: 64,
      reputation: 43,
      status: "active",
      position: { x: 83.2, y: 67.1 },
      currentAction: "buy_food",
      personality: {
        morality: 44,
        empathy: 31,
        ambition: 83,
        risk: 68,
        traits: ["greedy", "curious"],
      },
    },
    {
      id: "citizen_lina",
      name: "Lina",
      role: "medic",
      districtId: "civic",
      destinationDistrictId: "civic",
      factionId: "council",
      money: 33,
      hunger: 28,
      energy: 81,
      mood: 77,
      reputation: 72,
      status: "active",
      position: { x: 49.4, y: 38.8 },
      currentAction: "help_neighbor",
      personality: {
        morality: 74,
        empathy: 91,
        ambition: 54,
        risk: 34,
        traits: ["generous"],
      },
    },
    {
      id: "citizen_rio",
      name: "Rio",
      role: "builder",
      districtId: "homes",
      destinationDistrictId: "workshop",
      factionId: "shadows",
      money: 18,
      hunger: 61,
      energy: 52,
      mood: 49,
      reputation: 36,
      status: "active",
      position: { x: 16.2, y: 65.8 },
      currentAction: "rest",
      personality: {
        morality: 29,
        empathy: 24,
        ambition: 76,
        risk: 72,
        traits: ["impulsive", "secretive"],
      },
    },
    {
      id: "citizen_sofia",
      name: "Sofia",
      role: "baker",
      districtId: "market",
      destinationDistrictId: "market",
      factionId: "exchange",
      money: 29,
      hunger: 35,
      energy: 70,
      mood: 68,
      reputation: 51,
      status: "active",
      position: { x: 83.2, y: 67.1 },
      currentAction: "work",
      personality: {
        morality: 58,
        empathy: 47,
        ambition: 72,
        risk: 46,
        traits: ["curious", "disciplined"],
      },
    },
    {
      id: "citizen_leo",
      name: "Leo",
      role: "farmer",
      districtId: "farm",
      destinationDistrictId: "farm",
      factionId: "guild",
      money: 21,
      hunger: 49,
      energy: 78,
      mood: 63,
      reputation: 55,
      status: "active",
      position: { x: 73.0, y: 80.1 },
      currentAction: "work",
      personality: {
        morality: 69,
        empathy: 66,
        ambition: 42,
        risk: 31,
        traits: ["disciplined"],
      },
    },
    {
      id: "citizen_nia",
      name: "Nia",
      role: "trader",
      districtId: "market",
      destinationDistrictId: "market",
      factionId: "exchange",
      money: 52,
      hunger: 42,
      energy: 62,
      mood: 59,
      reputation: 39,
      status: "active",
      position: { x: 83.2, y: 67.1 },
      currentAction: "exploit_market",
      personality: {
        morality: 37,
        empathy: 36,
        ambition: 88,
        risk: 74,
        traits: ["greedy", "curious"],
      },
    },
    {
      id: "citizen_omar",
      name: "Omar",
      role: "builder",
      districtId: "workshop",
      destinationDistrictId: "workshop",
      factionId: "guild",
      money: 27,
      hunger: 45,
      energy: 69,
      mood: 66,
      reputation: 61,
      status: "active",
      position: { x: 49.5, y: 84.1 },
      currentAction: "work",
      personality: {
        morality: 63,
        empathy: 57,
        ambition: 65,
        risk: 39,
        traits: ["disciplined", "generous"],
      },
    },
    {
      id: "citizen_iris",
      name: "Iris",
      role: "medic",
      districtId: "civic",
      destinationDistrictId: "civic",
      factionId: "council",
      money: 36,
      hunger: 31,
      energy: 73,
      mood: 74,
      reputation: 70,
      status: "active",
      position: { x: 49.4, y: 38.8 },
      currentAction: "help_neighbor",
      personality: {
        morality: 79,
        empathy: 84,
        ambition: 51,
        risk: 28,
        traits: ["generous", "curious"],
      },
    },
    {
      id: "citizen_vale",
      name: "Vale",
      role: "trader",
      districtId: "civic",
      destinationDistrictId: "workshop",
      factionId: "shadows",
      money: 45,
      hunger: 57,
      energy: 55,
      mood: 52,
      reputation: 32,
      status: "active",
      position: { x: 49.4, y: 38.8 },
      currentAction: "faction_campaign",
      personality: {
        morality: 33,
        empathy: 29,
        ambition: 82,
        risk: 63,
        traits: ["secretive", "impulsive"],
      },
    },
    {
      id: "citizen_mara",
      name: "Mara",
      role: "officer",
      districtId: "police",
      destinationDistrictId: "police",
      factionId: "council",
      money: 31,
      hunger: 39,
      energy: 76,
      mood: 62,
      reputation: 64,
      status: "active",
      position: { x: 18.0, y: 45.6 },
      currentAction: "police_patrol",
      personality: {
        morality: 71,
        empathy: 58,
        ambition: 63,
        risk: 52,
        traits: ["disciplined"],
      },
    },
  ],
  tasks: [],
  events: [
    {
      id: "seed_event_0001",
      tick: 0,
      title: "Morning begins",
      description: "The town starts with enough food, a few jobs, and mixed motives.",
      severity: "info",
    },
  ],
};
